get http://localhost:5000/note

###

POST http://localhost:5000/tambah-note
Content-Type: application/json

{
    "title": "cek",
    "note": "cek"
}

###

PUT http://localhost:5000/edit-note/2
Content-Type: application/json

{
    "title": "gantiii",
    "note": "uhuyy"
}

###
DELETE http://localhost:5000/delete-note/1